language: node_js
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
cache:
  bundler: true
  directories:
    - node_modules
    - $HOME/.rvm
    - $HOME/.nvm
install:
  - npm i pm2 http-server contentascode/broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=iilab
    - CONFIG_REPO=contentascode
    - secure: >
        "ePKtrUNdYEtN2Uf36QvUhda5GHElaF8EdbTdNszrG7BsZc8H/ndYkCswDeZx6RS/v9MVBPWQWDaOQQ3PlXLJ+PREVkD49lzno60pVjnqDPCA4OtakPssQXQqOOlD861UzPyCbPyD2VvqLvTi2vufgzZMR3k4Sz8Jb+71LQxVd9nQLOf/2DDBkyKYpdwf9tFQa1PRH/UHJ2RkzThmX0m4W8ffNYy1KeFhlpJfj7Py8UvOZYAdWI+2WljVqEibIyLsCiZKImrrWkYP/YhqwUa0AWkvMLPhGowGuVPyzLSFk7vi5DWg4vmrUN0sxds4tsrUV0nvCvH1qYHLJ7y9GAnLUK1THUWXfQAUtZfJD0tKjIiUSFAx7KdHBQi0vXSQxMnT+8J9oCxkkH5DxKzukYUxIzHD4BZGD9inP+swgkq5yweErnvPpSM6eWmJuxJn1URsJT8EQ8ESfeDWMLynMUsPWvHZFkEta2Ms43S8EalREu8MbuL8A5i1w3e1mMjImiQDraBix9KnXClcFLzhHVR6xlovQJXqQV271LfSbQiK3/IOcxPT5Uyh46zX3BxEp2wc81vlLl/Fmb5SlW553SYMk9XuDBPxUNv8Ze9LTBn1Tmvt2kAxAGBJo/Gktk+s1ukguW24hS7CzTmYIabAKEwxdQp13qAKZ72AM8+Jk597OBk="
