language: node_js
sudo: false
node_js:
  - '4.2'
branches:
  except:
    - gh-pages
cache:
  bundler: true
  directories:
    - node_modules
install:
  - npm i pm2 http-server broken-link-checker -g
  - "rvm install $(sed 's/ruby-//g' .ruby-version)"
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
    - GH_USERNAME=jmatsushita
    - CONFIG_OWNER=iilab
    - CONFIG_REPO=contentascode
    - secure: >
        "7iGodkRzN2rlFUeYRSU1qQ8BVA2q1LKwruF7re2gQVIt29wV55xxib1ui8Hh+Jx8JmnU5rc7hOmXzD0WZhxxifavm6CQAwrjcoAUJyUvFSXAyU4kSSAgwg4ac61SFOd3tQH2ySfiNdg2HANWp8q3Vzsv2gsWkSrts6AIRRx2b1At2CiQ+xZhHpJAALWdJ/pRJsV6fOoShxKPSJlDZur4I4yMtMnIi7nE+QziVAmt2HJsWZO5f8hSv159ejr3/lJ5/EV7DCRwzlb01k1clN3ySRjVHLjt60262Eowc10wfLeGLquu1mdP/JcUGIUtWdQoeiGb34pS+jTjgaIj1UZzlE1qLpy3Q/Q5DAZrq9QiubfqECqI1coGAN47ONA6g40+ZjTflHazq/QeQUAOTFt5wZLiR9YtH6/naaYwjZx2qXGXwfRIXdMvGICedBgF7d1+o8gb1XpWjR30LRwKdlGJoLzBY6PHwRSP2RqoCEsS6U0zKYVyUTyhadwxiej4cK0+ZqQk7h4YVm6w+RAC++4gO8iZzJDGKP2mz3nXubuKVCEwKlKOWqo0La8y2+2/0DpJ5a8dbxEiPcuUGG5YZkQkKuDG1/MX2OByuHztGqCYzHVG7o+R3PE5JkXd60MA6bXlgNQyp1ZW9Maz1wXJnjm48JpPhdFaHOvuVXyZKWjJ/zw="
